# Generated by Django 4.1.3 on 2022-12-05 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_model',
        ),
    ]
